print("iniciamos la segunda parte")
print("iniciamos","la","segunda parte",end="***\n")
print("iniciamos","la","segunda parte",sep="$$$")
print("observan la separacion "*2)
print("Separar\n texto en variables\n lineas")

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)
